version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: tiny_http
    versions:
    - 0.7.0
    - 0.8.0
  - dependency-name: url
    versions:
    - 2.2.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: rust
    versions:
    - 1.49.0
    - 1.50.0
