[package]
name = "tiny-http-piping-server"
version = "0.1.0-SNAPSHOT"
authors = ["Ryo Ota <nwtgck@gmail.com>"]
edition = "2018"

[dependencies]
tiny_http = "0.6"
futures = "0.1"
tokio = "0.1"
url = "2.1"
structopt = "0.3"
